# Model Architecture
model:
  use_concat: True
  max_seq_length: 95
  max_nmr_length: 190
  max_memory_length: 32
  embed_dim: 128
  num_heads: 2
  num_layers: 3
  dropout: 0.0
  resample_size: 1000

# Training Parameters
training:
  batch_size: 32
  test_batch_size: 1
  num_epochs: 1
  learning_rate: [1e-5, 5e-5, 1e-4, 5e-4, 1e-3, 5e-3]  # List of LRs to try
  min_learning_rate: 1.0e-5
  validation_frequency: 50
  logging_frequency: 10
  save_frequency: 1000

# Scheduler
scheduler:
  type: cosine
  warmup_steps: 100


# Data
data:
  use_parquet: False
  data_dir: "data_extraction/multimodal_spectroscopic_dataset"
  binary_dir: "preprocessed_binaries"
  test_size: 20
  val_size: 0.001
  preprocessed: False

# Logging
wandb:
  project: "smiles-generation-sweep"  # Changed project name for sweep
  base_run_name: "lr_sweep"           # Changed run name for sweep
  log_examples: true 