# Model Architecture
model:
  use_concat: True
  max_seq_length: 80
  max_nmr_length: 190
  max_memory_length: 32
  embed_dim: 512
  num_heads: 4
  num_layers: 6
  dropout: 0.1
  resample_size: 1000

# Training Parameters
training:
  batch_size: 32
  test_batch_size: 1
  num_epochs: 10
  learning_rate: 1.0e-4
  min_learning_rate: 1.0e-5
  validation_frequency: 50
  logging_frequency: 10
  save_frequency: 1000

# Scheduler
scheduler:
  type: cosine
  warmup_steps: 100


# Data
data:
  use_parquet: False
  data_dir: "data_extraction/multimodal_spectroscopic_dataset"
  binary_dir: "preprocessed_binaries"
  test_size: 20
  val_size: 0.001
  preprocessed: False

# Logging
wandb:
  project: "smiles-generation"
  base_run_name: "smiles_gen"
  log_examples: true 